enum ErrorCodes {
  CANNOT_KICK_ANOTHER_USER = 'CANNOT_KICK_ANOTHER_USER',
  CONNECTION_ID_ALREADY_REGISTERED = 'CONNECTION_ID_ALREADY_REGISTERED',
  CONNECTION_ID_INVALID = 'CONNECTION_ID_INVALID',
  CONNECTION_NOT_JOINED = 'CONNECTION_NOT_JOINED',
  ROOM_NOT_STARTED = 'ROOM_NOT_STARTED',
  ROOM_STARTED = 'ROOM_STARTED',
  USER_PLACE_ASSIGNED = 'USER_PLACE_ASSIGNED',
  USER_PLACE_EMPTY = 'USER_PLACE_EMPTY',
  USER_PLACE_NOT_ALLOWED = 'USER_PLACE_NOT_ALLOWED',
};

export default ErrorCodes;
