enum ErrorCodes {
  CONNECTION_ID_ALREADY_REGISTERED = 'CONNECTION_ID_ALREADY_REGISTERED',
  CONNECTION_ID_INVALID = 'CONNECTION_ID_INVALID',
  CONNECTION_NOT_JOINED = 'CONNECTION_NOT_JOINED',
  ROOM_STARTED = 'ROOM_STARTED',
  ROOM_NOT_STARTED = 'ROOM_NOT_STARTED',
};

export default ErrorCodes;
