enum ErrorCodes {
  CONNECTION_ID_ALREADY_REGISTERED = 'CONNECTION_ID_ALREADY_REGISTERED',
  CONNECTION_ID_INVALID = 'CONNECTION_ID_INVALID',
  CONNECTION_NOT_JOINED = 'CONNECTION_NOT_JOINED',
  GAME_EXISTS = 'GAME_EXISTS',
  GAME_NOT_EXISTS = 'GAME_NOT_EXISTS',
};

export default ErrorCodes;
